/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-secondary-fixed": "#3b002c",
          "secondary-fixed-dim": "#ffaedd",
          "surface-container-lowest": "#0e0e0e",
          "on-tertiary-container": "#e4edff",
          "on-secondary": "#60004a",
          "surface-container-highest": "#353534",
          "on-tertiary-fixed": "#001c3b",
          "secondary": "#ffaedd",
          "surface-container-low": "#1c1b1b",
          "surface-tint": "#c9beff",
          "error": "#ffb4ab",
          "outline-variant": "#484555",
          "secondary-container": "#ba0091",
          "surface-container-high": "#2a2a2a",
          "tertiary-fixed": "#d5e3ff",
          "primary-fixed-dim": "#c9beff",
          "inverse-surface": "#e5e2e1",
          "tertiary-container": "#006bc5",
          "on-secondary-container": "#ffd5ea",
          "surface": "#131313",
          "inverse-on-surface": "#313030",
          "on-primary": "#2f009b",
          "tertiary-fixed-dim": "#a6c8ff",
          "on-tertiary": "#00315f",
          "on-surface-variant": "#c9c4d8",
          "secondary-fixed": "#ffd8eb",
          "on-secondary-fixed-variant": "#880069",
          "on-error": "#690005",
          "on-error-container": "#ffdad6",
          "on-primary-fixed-variant": "#450ed2",
          "background": "#131313",
          "primary-fixed": "#e5deff",
          "on-tertiary-fixed-variant": "#004786",
          "inverse-primary": "#5e3ae9",
          "surface-dim": "#131313",
          "error-container": "#93000a",
          "surface-variant": "#353534",
          "tertiary": "#a6c8ff",
          "surface-container": "#201f1f",
          "on-primary-container": "#f0eaff",
          "outline": "#938ea1",
          "primary-container": "#6b4af6",
          "primary": "#c9beff",
          "on-primary-fixed": "#1b0063",
          "surface-bright": "#3a3939",
          "on-background": "#e5e2e1",
          "on-surface": "#e5e2e1"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Manrope"],
          "body": ["Inter"],
          "label": ["Inter"]
      }
    },
  },
  plugins: [],
};
